apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-api.yaml
  - platform-api-router.yaml
  - platform-api-egress.yaml
  - execution-v2-workload.yaml
  - execution-v2-network-policy.yaml
