apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - open-terminal-pvc.yaml
  - open-terminal-deployment.yaml
  - open-terminal-service.yaml
  - open-terminal-networkpolicy.yaml
  - ingress.yaml
  - ingress-networkpolicy.yaml
