apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-terminal-workspace
  namespace: openwebui
  labels:
    app.kubernetes.io/name: open-terminal
    app.kubernetes.io/part-of: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
